@startuml usecase.png

title usecase:03 

actor 競技者 as user

left to right direction

skinparam usecase {
  BackgroundColor<<MissUseCase>> #DD6666
  BackgroundColor<<Mitigate>> YellowGreen
  ArrowColor #333399
}

skinparam actor {
  BackgroundColor<<NegativeActor>> Black
}

actor 外乱光 as noise <<NegativeActor>>
actor 段差   as ramp  <<NegativeActor>>

package '2015年度コース走行システム' {

  usecase 走行を開始する          as defalut

  usecase 通常走行する            as normal
  usecase 難所走行する            as different
  usecase 例外走行する            as exception

  'usecase 黒線追跡する            as line
  usecase ガレージを攻略する      as grage
  usecase ルックアップ攻略をする  as lookup
  usecase フィギュアLを攻略する   as figureL

  usecase 復帰走行する            as return    <<Mitigate>>
  usecase 緊急停止する            as stop      <<Mitigate>>

  usecase コースアウトする        as courseout <<MissUseCase>>
  usecase 転倒する                as falling   <<MissUseCase>>

  usecase 環境情報を取得する      as getenv

  usecase 電灯の配置を取得する    as getlight
  usecase キャリブレーションする  as calb

  user -- defalut
  user -- getenv

  defalut ..> normal    : <<include>>
  defalut ..> different : <<include>>
  defalut ..> exception : <<include>>

  grage   <.. courseout : <<脅威>>
  figureL <.. courseout
  lookup  <.. courseout

  figureL <.. falling : <<脅威>>
  lookup  <.. falling

  different <|-- grage
  different <|-- lookup
  different <|-- figureL

  exception <|-- return
  exception <|-- stop

  getenv ..> getlight  : <<include>>
  getenv ..> calb      : <<include>>

  courseout -- noise
  courseout -- ramp
  falling   -- ramp

  stop   ..>  falling   : <<緩和>>
  return ..>  courseout : <<緩和>>

}

@enduml
