@startuml linetrace.png
hide footbox

' Actor
actor       競技者       as Player
' Boundly
participant UI                       as UI
participant "SelectMenu:Menu"        as SelectMenu
participant "ExecMenu:Menu"          as ExecMenu
participant "RunMode:Mode"           as RunMode
' Cntroller
participant Runner                   as Runner
participant RunStrategy              as RunStrategy
participant RunMethod                as RunMethod
participant RunStyle                 as RunStyle
' Entity
participant EV3                      as EV3
participant "RunMotor:Motor"         as RunMotor
participant "LighnertSensor:Sensor"     as LightSensor

Player -> UI
activate Player
deactivate Player
activate UI
  UI  -> SelectMenu : select()
  UI <-- SelectMenu : selectedMenu
  activate SelectMenu
  deactivate SelectMenu
  UI  -> ExecMenu : execMenu(this.selectedMenu)
  activate ExecMenu
    ExecMenu  -> Runner : run()
    activate Runner
      Runner  -> EV3 : << new >>
      activate EV3
        Runner <-- EV3 : ev3
        EV3  -> RunMotor : << new >>
        activate RunMotor
          Runner <-- RunMotor : motor
        deactivate RunMotor
        EV3  -> LightSensor : << new >>
        activate LightSensor
          Run <-- LightSensor : LightSensor
        deactivate LightSensor
      deactivate EV3
      Runner -> RunStrategy : exec(ev3)
      activate RunStrategy
        RunStrategy  -> RunStyle : transform()
        activate RunStyle
        deactivate RunStyle
        RunStrategy  -> RunMethod : calcTreshold()
        activate RunMethod
          RunStrategy <-- RunMethod : turn
        deactivate RunMethod
      deactivate RunStrategy
    deactivate Runner
  deactivate ExecMenu
deactivate UI

@enduml
